// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACSiA5YUpZoATxHVgs0bso_XLz35fbSD0',
    appId: '1:717678124764:web:1e14ef8d9bbca424f91e19',
    messagingSenderId: '717678124764',
    projectId: 'memoire2026-467c9',
    authDomain: 'memoire2026-467c9.firebaseapp.com',
    storageBucket: 'memoire2026-467c9.firebasestorage.app',
    measurementId: 'G-YMGBDBB7SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo4CsPqB8BxHtuhTxFep0qUVnJw88ID4g',
    appId: '1:717678124764:android:c1dad437160f92d5f91e19',
    messagingSenderId: '717678124764',
    projectId: 'memoire2026-467c9',
    storageBucket: 'memoire2026-467c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo31S6pjHvl-ZEuS3hY_KqHirh3xkPtmE',
    appId: '1:717678124764:ios:87d3752103e7a38ff91e19',
    messagingSenderId: '717678124764',
    projectId: 'memoire2026-467c9',
    storageBucket: 'memoire2026-467c9.firebasestorage.app',
    iosClientId: '717678124764-dpjb6q6800otdvmbkkrcrc6hc44jdql8.apps.googleusercontent.com',
    iosBundleId: 'com.example.memoire2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo31S6pjHvl-ZEuS3hY_KqHirh3xkPtmE',
    appId: '1:717678124764:ios:87d3752103e7a38ff91e19',
    messagingSenderId: '717678124764',
    projectId: 'memoire2026-467c9',
    storageBucket: 'memoire2026-467c9.firebasestorage.app',
    iosClientId: '717678124764-dpjb6q6800otdvmbkkrcrc6hc44jdql8.apps.googleusercontent.com',
    iosBundleId: 'com.example.memoire2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACSiA5YUpZoATxHVgs0bso_XLz35fbSD0',
    appId: '1:717678124764:web:ff76a349d9572313f91e19',
    messagingSenderId: '717678124764',
    projectId: 'memoire2026-467c9',
    authDomain: 'memoire2026-467c9.firebaseapp.com',
    storageBucket: 'memoire2026-467c9.firebasestorage.app',
    measurementId: 'G-63TJ5LRGCF',
  );
}
